---
name: "Docker Image CI"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      -
        name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: us-east-2
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      -
        id: login-ecr
        name: "Login to Amazon ECR"
        uses: aws-actions/amazon-ecr-login@v1
      -
        env:
          ECR_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY: prometheus_remote_kinesis
          LATEST: latest
        name: "Get submodules, build the Docker image, push to AWS ECR"
        run: |
          GIT_REVISION=$(git describe --always)
          echo "building ${ECR_REGISTRY}/{ECR_REPOSITORY}:${LATEST}"
          echo "building ${ECR_REGISTRY}/{ECR_REPOSITORY}:${GIT_REVISION}"
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${LATEST} -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${GIT_REVISION} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY} --all-tags
